import { Module } from '@/types/module.types';

export const MODULES: Module[] = [
  {
    id: 'photography',
    title: 'Photographie Professionnelle',
    description: 'Maîtrise les fondamentaux de la photographie en combinant culture artistique, technique d\'exposition et composition visuelle.',
    icon: '📷',
    color: '#ec4899',
    duration: '4 semaines',
    totalXP: 1000,
    startDate: '2025-11-01',
    endDate: '2025-11-30',
    level: 'beginner',
    badge: '🏆 Œil d\'Aigle',
    weeks: [
      {
        weekNumber: 1,
        title: 'Culture & Fondations',
        objective: 'Comprendre l\'histoire de la photographie et assimiler le triangle d\'exposition',
        totalXP: 420,
        days: [
          {
            dayNumber: 1,
            title: 'Histoire de la photographie',
            duration: 30,
            xp: 50,
            completed: false,
            activities: [
              {
                id: 'photo-w1d1-1',
                type: 'lecture',
                title: 'Lecture : Histoire de la photo (origines)',
                duration: 30,
                xp: 50,
                completed: false,
              },
            ],
          },
          {
            dayNumber: 2,
            title: 'Les grands photographes',
            duration: 20,
            xp: 40,
            completed: false,
            activities: [
              {
                id: 'photo-w1d2-1',
                type: 'video',
                title: 'Vidéo interactive : Les grands photographes',
                duration: 20,
                xp: 40,
                completed: false,
              },
            ],
          },
          {
            dayNumber: 3,
            title: 'Quiz culture photo',
            duration: 15,
            xp: 60,
            completed: false,
            activities: [
              {
                id: 'photo-w1d3-1',
                type: 'quiz',
                title: 'Quiz : Culture photographique',
                duration: 15,
                xp: 60,
                completed: false,
              },
            ],
          },
          {
            dayNumber: 4,
            title: 'Triangle d\'exposition',
            duration: 45,
            xp: 80,
            completed: false,
            activities: [
              {
                id: 'photo-w1d4-1',
                type: 'lecture',
                title: 'Cours : Le triangle d\'exposition (théorie)',
                duration: 45,
                xp: 80,
                completed: false,
              },
            ],
          },
          {
            dayNumber: 5,
            title: 'Réglages d\'exposition',
            duration: 30,
            xp: 70,
            completed: false,
            activities: [
              {
                id: 'photo-w1d5-1',
                type: 'exercise',
                title: 'Exercice : Réglages d\'exposition guidés',
                duration: 30,
                xp: 70,
                completed: false,
              },
            ],
          },
          {
            dayNumber: 6,
            title: 'Mini-défi paramètres',
            duration: 60,
            xp: 100,
            completed: false,
            activities: [
              {
                id: 'photo-w1d6-1',
                type: 'exercise',
                title: 'Mini-défi : 3 photos avec paramètres imposés',
                duration: 60,
                xp: 100,
                completed: false,
              },
            ],
          },
          {
            dayNumber: 7,
            title: 'Repos créatif',
            duration: 0,
            xp: 20,
            completed: false,
            activities: [
              {
                id: 'photo-w1d7-1',
                type: 'lecture',
                title: 'Repos créatif + révision libre',
                duration: 0,
                xp: 20,
                completed: false,
              },
            ],
          },
        ],
      },
      {
        weekNumber: 2,
        title: 'Technique de Base',
        objective: 'Maîtriser ouverture, vitesse, ISO et mise au point',
        totalXP: 520,
        days: [
          {
            dayNumber: 1,
            title: 'Ouverture et profondeur',
            duration: 30,
            xp: 60,
            completed: false,
            activities: [
              {
                id: 'photo-w2d1-1',
                type: 'lecture',
                title: 'Cours : Ouverture et profondeur de champ',
                duration: 30,
                xp: 60,
                completed: false,
              },
            ],
          },
          {
            dayNumber: 2,
            title: 'Portraits en pratique',
            duration: 45,
            xp: 90,
            completed: false,
            activities: [
              {
                id: 'photo-w2d2-1',
                type: 'exercise',
                title: 'Exercice : Portraits avec différentes ouvertures',
                duration: 45,
                xp: 90,
                completed: false,
              },
            ],
          },
          {
            dayNumber: 3,
            title: 'Vitesse d\'obturation',
            duration: 30,
            xp: 60,
            completed: false,
            activities: [
              {
                id: 'photo-w2d3-1',
                type: 'lecture',
                title: 'Cours : Vitesse d\'obturation et mouvement',
                duration: 30,
                xp: 60,
                completed: false,
              },
            ],
          },
          {
            dayNumber: 4,
            title: 'Figer et flouter',
            duration: 45,
            xp: 90,
            completed: false,
            activities: [
              {
                id: 'photo-w2d4-1',
                type: 'exercise',
                title: 'Exercice : Figer et flouter le mouvement',
                duration: 45,
                xp: 90,
                completed: false,
              },
            ],
          },
          {
            dayNumber: 5,
            title: 'ISO et bruit',
            duration: 20,
            xp: 50,
            completed: false,
            activities: [
              {
                id: 'photo-w2d5-1',
                type: 'lecture',
                title: 'Cours : ISO et gestion du bruit',
                duration: 20,
                xp: 50,
                completed: false,
              },
            ],
          },
          {
            dayNumber: 6,
            title: 'Shooting basse lumière',
            duration: 60,
            xp: 120,
            completed: false,
            activities: [
              {
                id: 'photo-w2d6-1',
                type: 'exercise',
                title: 'Défi : Shooting en basse lumière',
                duration: 60,
                xp: 120,
                completed: false,
              },
            ],
          },
          {
            dayNumber: 7,
            title: 'Feedback personnalisé',
            duration: 30,
            xp: 50,
            completed: false,
            activities: [
              {
                id: 'photo-w2d7-1',
                type: 'lecture',
                title: 'Feedback IA + corrections personnalisées',
                duration: 30,
                xp: 50,
                completed: false,
              },
            ],
          },
        ],
      },
      {
        weekNumber: 3,
        title: 'Composition & Lumière',
        objective: 'Créer des images fortes par la composition et la maîtrise de la lumière',
        totalXP: 590,
        days: [
          {
            dayNumber: 1,
            title: 'Règles de composition',
            duration: 35,
            xp: 70,
            completed: false,
            activities: [
              {
                id: 'photo-w3d1-1',
                type: 'lecture',
                title: 'Cours : Les règles de composition',
                duration: 35,
                xp: 70,
                completed: false,
              },
            ],
          },
          {
            dayNumber: 2,
            title: 'Recadrage créatif',
            duration: 30,
            xp: 60,
            completed: false,
            activities: [
              {
                id: 'photo-w3d2-1',
                type: 'exercise',
                title: 'Exercice : Recadrage créatif de tes anciennes photos',
                duration: 30,
                xp: 60,
                completed: false,
              },
            ],
          },
          {
            dayNumber: 3,
            title: 'Lumière naturelle',
            duration: 30,
            xp: 70,
            completed: false,
            activities: [
              {
                id: 'photo-w3d3-1',
                type: 'lecture',
                title: 'Cours : La lumière naturelle (Golden/Blue Hour)',
                duration: 30,
                xp: 70,
                completed: false,
              },
            ],
          },
          {
            dayNumber: 4,
            title: 'Shooting Golden Hour',
            duration: 60,
            xp: 130,
            completed: false,
            activities: [
              {
                id: 'photo-w3d4-1',
                type: 'exercise',
                title: 'Mission : Shooting Golden Hour',
                duration: 60,
                xp: 130,
                completed: false,
              },
            ],
          },
          {
            dayNumber: 5,
            title: 'Post-production',
            duration: 40,
            xp: 80,
            completed: false,
            activities: [
              {
                id: 'photo-w3d5-1',
                type: 'lecture',
                title: 'Cours : Post-production de base',
                duration: 40,
                xp: 80,
                completed: false,
              },
            ],
          },
          {
            dayNumber: 6,
            title: 'Retouche guidée',
            duration: 60,
            xp: 100,
            completed: false,
            activities: [
              {
                id: 'photo-w3d6-1',
                type: 'exercise',
                title: 'Exercice : Retouche guidée de 3 photos',
                duration: 60,
                xp: 100,
                completed: false,
              },
            ],
          },
          {
            dayNumber: 7,
            title: 'Challenge photo',
            duration: 15,
            xp: 80,
            completed: false,
            activities: [
              {
                id: 'photo-w3d7-1',
                type: 'exercise',
                title: 'Challenge : Soumets ta meilleure photo',
                duration: 15,
                xp: 80,
                completed: false,
              },
            ],
          },
        ],
      },
      {
        weekNumber: 4,
        title: 'Projet Final & Narration',
        objective: 'Réaliser ta série photographique complète',
        totalXP: 580,
        days: [
          {
            dayNumber: 1,
            title: 'Briefing projet',
            duration: 20,
            xp: 30,
            completed: false,
            activities: [
              {
                id: 'photo-w4d1-1',
                type: 'lecture',
                title: 'Briefing projet final + choix du thème',
                duration: 20,
                xp: 30,
                completed: false,
              },
            ],
          },
          {
            dayNumber: 2,
            title: 'Planification',
            duration: 120,
            xp: 100,
            completed: false,
            activities: [
              {
                id: 'photo-w4d2-1',
                type: 'project',
                title: 'Planification : repérages, mood board, story-board',
                duration: 120,
                xp: 100,
                completed: false,
              },
            ],
          },
          {
            dayNumber: 3,
            title: 'Shooting jour 1',
            duration: 180,
            xp: 200,
            completed: false,
            activities: [
              {
                id: 'photo-w4d3-1',
                type: 'project',
                title: 'Shooting : réalisation des 5 photos (jour 1)',
                duration: 180,
                xp: 200,
                completed: false,
              },
            ],
          },
          {
            dayNumber: 4,
            title: 'Post-production',
            duration: 120,
            xp: 120,
            completed: false,
            activities: [
              {
                id: 'photo-w4d4-1',
                type: 'project',
                title: 'Post-production de la série complète',
                duration: 120,
                xp: 120,
                completed: false,
              },
            ],
          },
          {
            dayNumber: 5,
            title: 'Finalisation',
            duration: 60,
            xp: 80,
            completed: false,
            activities: [
              {
                id: 'photo-w4d5-1',
                type: 'project',
                title: 'Finalisation : export, document explicatif',
                duration: 60,
                xp: 80,
                completed: false,
              },
            ],
          },
          {
            dayNumber: 6,
            title: 'Soumission finale',
            duration: 15,
            xp: 50,
            completed: false,
            activities: [
              {
                id: 'photo-w4d6-1',
                type: 'project',
                title: 'Soumission finale du projet',
                duration: 15,
                xp: 50,
                completed: false,
              },
            ],
          },
          {
            dayNumber: 7,
            title: 'Repos',
            duration: 0,
            xp: 0,
            completed: false,
            activities: [],
          },
        ],
      },
    ],
    theory: {
      title: 'Théorie & Histoire de la Photographie',
      sections: [
        {
          id: 'theory-1',
          title: 'Les origines de la photographie',
          content: 'La photographie naît en 1826 avec Joseph Nicéphore Niépce...',
        },
      ],
    },
    practice: {
      title: 'Technique & Pratique',
      exercises: [],
    },
    finalProject: {
      title: 'Raconte ton histoire en 5 photos',
      description: 'Créer une mini-série photographique cohérente de 5 photographies qui racontent une histoire.',
      requirements: [
        'Au moins 1 photo en grande ouverture (f/1.4 - f/2.8)',
        'Au moins 1 photo en petite ouverture (f/8 - f/16)',
        'Au moins 1 photo avec vitesse rapide (≥1/500)',
        'Variété dans les cadrages',
        'Cohérence esthétique',
      ],
      criteria: [
        { name: 'Maîtrise technique', points: 30, description: 'Triangle d\'exposition, netteté' },
        { name: 'Composition', points: 25, description: 'Règle des tiers, équilibre' },
        { name: 'Intention artistique', points: 20, description: 'Message, émotion' },
        { name: 'Cohérence', points: 15, description: 'Les 5 photos fonctionnent ensemble' },
        { name: 'Post-production', points: 10, description: 'Retouche harmonieuse' },
      ],
      maxPoints: 100,
      deadline: '2025-11-30',
    },
  },
  {
    id: 'videography',
    title: 'Vidéaste & Réalisateur',
    description: 'Maîtrise les fondamentaux de la réalisation audiovisuelle en combinant culture cinématographique et techniques de prise de vue.',
    icon: '🎬',
    color: '#8b5cf6',
    duration: '4 semaines',
    totalXP: 1200,
    startDate: '2025-12-01',
    endDate: '2025-12-31',
    level: 'beginner',
    badge: '🎥 Réalisateur Émergent',
    weeks: [
      {
        weekNumber: 1,
        title: 'Culture Cinéma & Grammaire Visuelle',
        objective: 'S\'imprégner de l\'histoire du cinéma et maîtriser les échelles de plans',
        totalXP: 530,
        days: [],
      },
      {
        weekNumber: 2,
        title: 'Technique Vidéo & Son',
        objective: 'Maîtriser les réglages caméra et l\'enregistrement audio',
        totalXP: 620,
        days: [],
      },
      {
        weekNumber: 3,
        title: 'Lumière, Direction & Montage',
        objective: 'Éclairer comme un pro et découvrir le montage narratif',
        totalXP: 710,
        days: [],
      },
      {
        weekNumber: 4,
        title: 'Projet Final - Court-Métrage',
        objective: 'Produire ton court-métrage d\'1 minute sans dialogue',
        totalXP: 920,
        days: [],
      },
    ],
    theory: { title: 'Théorie & Histoire du Cinéma', sections: [] },
    practice: { title: 'Technique & Pratique', exercises: [] },
    finalProject: {
      title: 'Court-métrage d\'1 minute sans dialogue',
      description: 'Réaliser un court-métrage narratif entièrement visuel.',
      requirements: [
        'Durée stricte : 50-60 secondes',
        'AUCUN dialogue',
        'Minimum 8 plans différents',
        'Au moins 1 mouvement de caméra fluide',
        'Au moins 3 échelles de plan',
      ],
      criteria: [
        { name: 'Narration visuelle', points: 25, description: 'Histoire claire, émotion' },
        { name: 'Technique vidéo', points: 20, description: 'Exposition, focus, stabilité' },
        { name: 'Cadrage', points: 15, description: 'Variété, esthétique' },
        { name: 'Lumière', points: 10, description: 'Éclairage intentionnel' },
        { name: 'Son', points: 10, description: 'Audio propre, design sonore' },
        { name: 'Montage', points: 10, description: 'Fluidité, rythme' },
        { name: 'Direction artistique', points: 10, description: 'Cohérence, originalité' },
      ],
      maxPoints: 100,
      deadline: '2025-12-31',
    },
  },
  {
    id: 'editing',
    title: 'Montage Vidéo Avancé',
    description: 'Maîtrise l\'art du montage vidéo comme outil narratif, rythmique et émotionnel.',
    icon: '✂️',
    color: '#06b6d4',
    duration: '4 semaines',
    totalXP: 1300,
    startDate: '2026-01-01',
    endDate: '2026-01-31',
    level: 'intermediate',
    badge: '🎞️ Monteur Virtuose',
    weeks: [
      {
        weekNumber: 1,
        title: 'Histoire du Montage & Bases',
        objective: 'Comprendre le montage comme art narratif et maîtriser les raccords',
        totalXP: 650,
        days: [],
      },
      {
        weekNumber: 2,
        title: 'Rythme, Timing & Son',
        objective: 'Maîtriser le rythme narratif et le mixage audio professionnel',
        totalXP: 720,
        days: [],
      },
      {
        weekNumber: 3,
        title: 'Étalonnage & Post-Production',
        objective: 'Créer un look colorimétrique professionnel',
        totalXP: 820,
        days: [],
      },
      {
        weekNumber: 4,
        title: 'Projet Final - Montage Narratif',
        objective: 'Produire ta vidéo finale montée de 2-3 minutes',
        totalXP: 1030,
        days: [],
      },
    ],
    theory: { title: 'Théorie & Histoire du Montage', sections: [] },
    practice: { title: 'Technique & Pratique', exercises: [] },
    finalProject: {
      title: 'Montage Narratif et Créatif (2-3 minutes)',
      description: 'Créer une vidéo montée qui démontre ta maîtrise complète du montage.',
      requirements: [
        'Durée : 2min00 à 3min00',
        'Minimum 15 plans différents',
        '3 types de raccords différents',
        'Variation de rythme',
        'Mixage audio 4 pistes',
        'Étalonnage cohérent',
      ],
      criteria: [
        { name: 'Narration', points: 20, description: 'Histoire, progression' },
        { name: 'Rythme', points: 20, description: 'Tempo, timing' },
        { name: 'Montage', points: 15, description: 'Raccords, transitions' },
        { name: 'Étalonnage', points: 15, description: 'Look cohérent' },
        { name: 'Mixage audio', points: 15, description: 'Niveaux, design sonore' },
        { name: 'Créativité', points: 10, description: 'Originalité' },
        { name: 'Finition', points: 5, description: 'Professionnalisme' },
      ],
      maxPoints: 100,
      deadline: '2026-01-31',
    },
  },
];